hydra:
  run:
    dir: ./experiments/CiPCL/${dataset}
  job:
    chdir: true

  job_logging:
    version: 1
    formatters:
      simple:
        format: '%(message)s'

device: "cuda:3"
class_order: "class_orders/MSCOCO36.yaml"
dataset_root: "../../DATA"
workdir: "../../pcl"
log_path: "metrics.json"
model_name: "../../Pretrained_models/OpenCLIP-Vit-B-16Plus/vit_b_16_plus_240.pt"

seed: 42
epoch: 1 
batch_size: 64
increment: ${initial_increment}
initial_increment: 1 
scenario: "class"
dataset: "MSCOCO36_translate"

weight_decay: 0
l2: 0
ce_method: 0

method: "translate"
lr: 1e-4
ls: 0.0


